/**
 * Imports every built-in block descriptor module for its registration side effect, so the palette
 * and load-time descriptor lookups see all built-in blocks. The import order here is the palette
 * display order. Adding a block means adding its descriptor module and one import line here.
 */

import "./importGLTFBlockDescriptor";
import "./readGLTFBlockDescriptor";
import "./gltfToUniversalBlockDescriptor";
import "./universalToGLTFBlockDescriptor";
import "./writeGLTFBlockDescriptor";
import "./legacyImportGLTFBlockDescriptor";
import "./legacyExportGLTFBlockDescriptor";
import "./importUSDBlockDescriptor";
import "./dracoCompressionBlockDescriptor";
import "./exportGLTFBlockDescriptor";
import "./ktx2CompressionBlockDescriptor";
import "./weldBlockDescriptor";
import "./dedupBlockDescriptor";
import "./pruneBlockDescriptor";
import "./weldVerticesBlockDescriptor";
import "./removeUnusedResourcesBlockDescriptor";
import "./removeDegenerateGeometryBlockDescriptor";
import "./fixFaceWindingBlockDescriptor";
import "./quantizeAttributesBlockDescriptor";
import "./simplifyMeshesBlockDescriptor";
import "./flattenBlockDescriptor";
import "./joinBlockDescriptor";
import "./flattenHierarchyBlockDescriptor";
import "./joinMeshesBlockDescriptor";
import "./splitMeshesByMaterialBlockDescriptor";
import "./normalsBlockDescriptor";
import "./centerBlockDescriptor";
import "./numberLiteralDescriptor";
import "./stringLiteralDescriptor";
import "./jsonLiteralDescriptor";
import "./mergeScenesDescriptor";
import "./mergeScenesBlockDescriptor";
import "./selectorDescriptor";
import "./getPropertyDescriptor";
import "./setPropertyDescriptor";
import "./importImageBlockDescriptor";
import "./exportImageBlockDescriptor";
import "./buildPBRMaterialDescriptor";
import "./resizeImageBlockDescriptor";
import "./convertImageFormatBlockDescriptor";
import "./flipImageBlockDescriptor";
import "./extractTextureDescriptor";
import "./compositeImageBlockDescriptor";
import "./setTextureDescriptor";
import "./importBabylonBlockDescriptor";
import "./importNodeGeometryBlockDescriptor";
import "./readNodeGeometryBlockDescriptor";
import "./nodeGeometryToUniversalBlockDescriptor";
import "./legacyImportNodeGeometryBlockDescriptor";
import "./usd2GLTFBlockDescriptor";
import "./usd2BabylonBlockDescriptor";
import "./gltf2BabylonBlockDescriptor";
import "./babylon2GLTFBlockDescriptor";
import "./evaluateNodeGeometryBlockDescriptor";
import "./decomposeGLTFMaterialBlockDescriptor";
import "./composeGLTFMaterialBlockDescriptor";
import "./customAggregateBlockDescriptor";
import "./getBabylonMeshBlockDescriptor";
import "./setBabylonPropertyBlockDescriptor";
import "./getUSDPrimBlockDescriptor";
import "./gltfSelectorBlockDescriptor";
import "./usdSelectorBlockDescriptor";
import "./babylonSelectorBlockDescriptor";
