import {
    RuntimeCorpusManifest,
    BoxAsset,
    ConeAsset,
    CylinderAsset,
    DeliveryBoxAsset,
    DialysisMachineAsset,
    ForkliftAsset,
    UR10Asset,
    ShelvesAsset,
    HospitalBedAsset,
    HospitalBedWrapperAsset,
    PlaceholderAsset,
    PlaneAsset,
    RobotArmAsset,
    RobotArmWrapperAsset,
    RoomAsset,
    SeahorseTextAsset,
    SphereAsset,
    StairsAsset,
    type IRuntimeCorpusEntry,
} from "./manifest";
import { readRuntimeCorpusText, readRuntimeCorpusBytes, RUNTIME_CORPUS_CDN_ROOT } from "./corpusText";

export {
    RuntimeCorpusManifest,
    BoxAsset,
    ConeAsset,
    CylinderAsset,
    DeliveryBoxAsset,
    DialysisMachineAsset,
    ForkliftAsset,
    UR10Asset,
    ShelvesAsset,
    HospitalBedAsset,
    HospitalBedWrapperAsset,
    PlaceholderAsset,
    PlaneAsset,
    RobotArmAsset,
    RobotArmWrapperAsset,
    RoomAsset,
    SeahorseTextAsset,
    SphereAsset,
    StairsAsset,
    type IRuntimeCorpusEntry,
    readRuntimeCorpusText,
    readRuntimeCorpusBytes,
    RUNTIME_CORPUS_CDN_ROOT,
};
