import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { NullEngine } from "core/Engines/nullEngine";
import { Scene } from "core/scene";
import { type ISceneLoaderAsyncResult, ImportMeshAsync } from "core/Loading/sceneLoader";
import { VertexBuffer } from "core/Buffers/buffer";
import { Vector3 } from "core/Maths/math.vector";
import "loaders/USD/usdFileLoader";

import { type IResolvedStage } from "loaders/USD/resolution/resolvedStage";
import { ResolveUsdStageAsync } from "loaders/USD/resolution/usdResolver";

import { RobotArmAsset } from "./runtimeCorpus/manifest";
import { readRuntimeCorpusText } from "./runtimeCorpus/corpusText";

// The Robot Arm file is ~25 MB. Parse/import once per describe block and share the read-only
// result across tests. Each test asserts independently against the shared data without mutation.

describe("USD runtime corpus - Robot Arm (resolved stage)", () => {
    let stage: IResolvedStage;

    beforeAll(async () => {
        stage = await ResolveUsdStageAsync(readRuntimeCorpusText(RobotArmAsset.fileName), "", RobotArmAsset.fileName, {});
    });

    it("resolves stage metadata with Z-up axis and metersPerUnit=0.01", () => {
        expect(stage.metadata.upAxis).toBe("Z");
        expect(stage.metadata.metersPerUnit).toBe(0.01);
        expect(stage.metadata.defaultPrimPath).toBe("/RobotArm");
    });

    it("resolves 7 meshes with subdivisionScheme none and authored face-varying normals", () => {
        expect(stage.meshes).toHaveLength(7);
        for (const mesh of stage.meshes) {
            expect(mesh.subdivisionScheme).toBe("none");
            // Normals are authored face-varying in the USDA, not generated by the loader.
            expect(mesh.normals).toBeDefined();
            expect(mesh.normals!.length).toBe(mesh.positions.length);
        }
    });

    it("resolves no UV sets on any mesh (none authored in the USDA)", () => {
        for (const mesh of stage.meshes) {
            expect(mesh.uvSets === undefined || mesh.uvSets.length === 0).toBe(true);
        }
    });

    it("emits stable diagnostics for all 3 unsupported MDL materials", () => {
        const mdlDiagnostics = stage.diagnostics.filter((d) => d.severity === "info" && /UsdPreviewSurface.*not found.*default material/i.test(d.message));
        expect(mdlDiagnostics).toHaveLength(3);

        const expectedPaths = ["/RobotArm/Looks/Aluminum_Polished", "/RobotArm/Looks/Metal_Black_Paint", "/RobotArm/Looks/Plastic_Thick_Translucent"];
        const reportedPaths = mdlDiagnostics.map((d) => d.path).sort();
        expect(reportedPaths).toEqual(expectedPaths.sort());
    });

    it("emits a warning diagnostic for the empty normalmap asset path", () => {
        const emptyPath = stage.diagnostics.find(
            (d) => d.severity === "warning" && d.path === "/RobotArm/Looks/Aluminum_Polished/Shader.inputs:normalmap_texture" && /empty path/i.test(d.message)
        );
        expect(emptyPath).toBeDefined();
    });

    it("emits a warning diagnostic for the absolute nonportable ORM texture path", () => {
        const absolutePath = stage.diagnostics.find(
            (d) => d.severity === "warning" && d.path === "/RobotArm/Looks/Aluminum_Polished/Shader.inputs:ORM_texture" && /absolute nonportable/i.test(d.message)
        );
        expect(absolutePath).toBeDefined();
    });

    it("resolves all 7 meshes despite unsupported material inputs", () => {
        expect(stage.meshes).toHaveLength(7);
        const totalIndices = stage.meshes.reduce((sum, m) => sum + m.indices.length, 0);
        expect(totalIndices).toBe(527_592);
    });
});

describe("USD runtime corpus - Robot Arm (Babylon adapter)", () => {
    let engine: NullEngine;
    let scene: Scene;
    let result: ISceneLoaderAsyncResult;

    beforeAll(async () => {
        engine = new NullEngine();
        scene = new Scene(engine);
        scene.useRightHandedSystem = true;
        result = await ImportMeshAsync(`data:${readRuntimeCorpusText(RobotArmAsset.fileName)}`, scene, {
            pluginExtension: ".usda",
            name: RobotArmAsset.fileName,
        });
    });

    afterAll(() => {
        scene.dispose();
        engine.dispose();
    });

    // -- Hierarchy --

    it("loads exactly 7 renderable meshes", () => {
        expect(result.meshes).toHaveLength(7);
    });

    it("produces the expected transform hierarchy: root RobotArm with 7 Xform children and Looks scope", () => {
        const robotArm = result.transformNodes.find((n) => n.name === "RobotArm");
        expect(robotArm).toBeDefined();

        const expectedXforms = ["obj_7", "obj_15_006", "obj_15_009", "obj_15_004", "obj_15_008", "obj_15_005", "obj_15_010"];
        for (const name of expectedXforms) {
            const xform = result.transformNodes.find((n) => n.name === name);
            expect(xform, `Expected Xform '${name}'`).toBeDefined();
            expect(xform!.parent?.name).toBe("RobotArm");
        }

        const looks = result.transformNodes.find((n) => n.name === "Looks");
        expect(looks).toBeDefined();
        expect(looks!.parent?.name).toBe("RobotArm");
    });

    it("parents each mesh under its Xform container", () => {
        const meshParentMap: Record<string, string> = {
            Mesh_001: "obj_7",
            Mesh_035: "obj_15_006",
            Mesh_038: "obj_15_009",
            Mesh_033: "obj_15_004",
            Mesh_037: "obj_15_008",
            Mesh_034: "obj_15_005",
            Mesh_031: "obj_15_010",
        };

        for (const [meshName, parentName] of Object.entries(meshParentMap)) {
            const mesh = result.meshes.find((m) => m.name === meshName);
            expect(mesh, `Expected mesh '${meshName}'`).toBeDefined();
            expect(mesh!.parent?.name).toBe(parentName);
        }
    });

    // -- Authored transforms --

    it("applies exact authored transforms on all 7 Xform nodes", () => {
        // Each Xform has: translate (unique), rotateXYZ = (0,0,0), scale = (0.04, 0.04, 0.04)
        const expectedTransforms: Record<string, { tx: number; ty: number; tz: number }> = {
            obj_7: { tx: -0.07087993621826172, ty: 0.07992386817932129, tz: 1.2649415731430054 },
            obj_15_006: { tx: -0.007185935974121094, ty: 0.37291955947875977, tz: 0.9694015979766846 },
            obj_15_009: { tx: 0.13338756561279297, ty: 0.242872953414917, tz: 0.7340124845504761 },
            obj_15_004: { tx: -0.4493532180786133, ty: 0.14801859855651855, tz: 1.4949501752853394 },
            obj_15_008: { tx: -0.037995338439941406, ty: 0.3861074447631836, tz: 0.5418595671653748 },
            obj_15_005: { tx: 0.11445903778076172, ty: -0.24316048622131348, tz: 2.1026813983917236 },
            obj_15_010: { tx: -0.036332130432128906, ty: -0.8647258281707764, tz: 1.7670966386795044 },
        };

        for (const [name, expected] of Object.entries(expectedTransforms)) {
            const xform = result.transformNodes.find((n) => n.name === name)!;
            expect(xform.position.x, `${name} pos.x`).toBeCloseTo(expected.tx, 4);
            expect(xform.position.y, `${name} pos.y`).toBeCloseTo(expected.ty, 4);
            expect(xform.position.z, `${name} pos.z`).toBeCloseTo(expected.tz, 4);
            expect(xform.scaling.x, `${name} scale.x`).toBeCloseTo(0.04, 4);
            expect(xform.scaling.y, `${name} scale.y`).toBeCloseTo(0.04, 4);
            expect(xform.scaling.z, `${name} scale.z`).toBeCloseTo(0.04, 4);
            // Authored rotateXYZ = (0,0,0) → identity quaternion
            expect(xform.rotationQuaternion, `${name} has rotation quaternion`).toBeDefined();
            expect(xform.rotationQuaternion!.x, `${name} rot.x`).toBeCloseTo(0, 5);
            expect(xform.rotationQuaternion!.y, `${name} rot.y`).toBeCloseTo(0, 5);
            expect(xform.rotationQuaternion!.z, `${name} rot.z`).toBeCloseTo(0, 5);
            expect(Math.abs(xform.rotationQuaternion!.w), `${name} rot.w`).toBeCloseTo(1, 5);
        }
    });

    // -- Geometry --

    it("produces authored face-varying normals on all meshes (not generated)", () => {
        for (const mesh of result.meshes) {
            const normals = mesh.getVerticesData(VertexBuffer.NormalKind);
            expect(normals, `Expected normals on '${mesh.name}'`).toBeDefined();
            expect(normals!.length).toBeGreaterThan(0);
        }
    });

    it("produces no UVs on any mesh (none authored in the USDA)", () => {
        for (const mesh of result.meshes) {
            const uvs = mesh.getVerticesData(VertexBuffer.UVKind);
            expect(uvs, `Expected no UVs on '${mesh.name}'`).toBeNull();
        }
    });

    it("produces the expected index counts per mesh", () => {
        const expectedCounts: Record<string, number> = {
            Mesh_001: 231_606,
            Mesh_035: 4_572,
            Mesh_038: 7_824,
            Mesh_033: 60_519,
            Mesh_037: 3_540,
            Mesh_034: 14_706,
            Mesh_031: 204_825,
        };

        for (const [meshName, expectedIndices] of Object.entries(expectedCounts)) {
            const mesh = result.meshes.find((m) => m.name === meshName);
            expect(mesh, `Expected mesh '${meshName}'`).toBeDefined();
            expect(mesh!.getTotalIndices(), `Index count for '${meshName}'`).toBe(expectedIndices);
        }
    });

    it("produces 527,592 total indices across all 7 meshes", () => {
        const totalIndices = result.meshes.reduce((sum, m) => sum + m.getTotalIndices(), 0);
        expect(totalIndices).toBe(527_592);
    });

    // -- Z-up and metersPerUnit conversion --

    it("enables right-handed scene mode for Z-up conversion", () => {
        expect(scene.useRightHandedSystem).toBe(true);
    });

    it("produces a stage root with -90° X rotation for Z-up and 0.01 unit scaling", () => {
        const stageRoot = result.transformNodes[0];
        expect(stageRoot.name).toBe("__usd_root__");

        const rotQ = stageRoot.rotationQuaternion;
        expect(rotQ).toBeDefined();
        expect(rotQ!.x).toBeCloseTo(-Math.sin(Math.PI / 4), 3);
        expect(rotQ!.y).toBeCloseTo(0, 5);
        expect(rotQ!.z).toBeCloseTo(0, 5);
        expect(rotQ!.w).toBeCloseTo(Math.cos(Math.PI / 4), 3);

        expect(stageRoot.scaling.x).toBeCloseTo(0.01, 5);
        expect(stageRoot.scaling.y).toBeCloseTo(0.01, 5);
        expect(stageRoot.scaling.z).toBeCloseTo(0.01, 5);
    });

    // -- Deterministic bounds --

    it("produces deterministic local bounds matching authored USD coordinate ranges", () => {
        let globalMinX = Infinity,
            globalMaxX = -Infinity;
        let globalMinY = Infinity,
            globalMaxY = -Infinity;
        let globalMinZ = Infinity,
            globalMaxZ = -Infinity;

        for (const mesh of result.meshes) {
            const positions = mesh.getVerticesData(VertexBuffer.PositionKind)!;
            for (let v = 0; v < positions.length; v += 3) {
                globalMinX = Math.min(globalMinX, positions[v]);
                globalMaxX = Math.max(globalMaxX, positions[v]);
                globalMinY = Math.min(globalMinY, positions[v + 1]);
                globalMaxY = Math.max(globalMaxY, positions[v + 1]);
                globalMinZ = Math.min(globalMinZ, positions[v + 2]);
                globalMaxZ = Math.max(globalMaxZ, positions[v + 2]);
            }
        }

        // Authored USD point extents (positions are stored in USD space; the stage root handles conversion)
        expect(globalMinX).toBeCloseTo(-436.25, 0);
        expect(globalMaxX).toBeCloseTo(18.86, 0);
        expect(globalMinY).toBeCloseTo(-31.05, 0);
        expect(globalMaxY).toBeCloseTo(42.21, 0);
        expect(globalMinZ).toBeCloseTo(-44.18, 0);
        expect(globalMaxZ).toBeCloseTo(25.99, 0);
    });

    it("produces deterministic aggregate world bounds after Z-up rotation and metersPerUnit=0.01 scaling", () => {
        // Each mesh is under an Xform with scale=0.04 and its own translate, under RobotArm (identity),
        // under the stage root (scale=0.01, Z-up rotation). The effective mesh-position scale is
        // 0.04 × 0.01 = 0.0004, plus the Xform translations × 0.01.
        const worldMin = new Vector3(Infinity, Infinity, Infinity);
        const worldMax = new Vector3(-Infinity, -Infinity, -Infinity);

        for (const mesh of result.meshes) {
            mesh.computeWorldMatrix(true);
            const bi = mesh.getBoundingInfo();
            worldMin.minimizeInPlace(bi.boundingBox.minimumWorld);
            worldMax.maximizeInPlace(bi.boundingBox.maximumWorld);
        }

        // World bounds should be non-degenerate and in a physically plausible range:
        // The Xform translations are in the range [-0.86, 2.10] in USD space, scaled by 0.01.
        // Mesh positions range to ±436 cm, scaled by 0.04×0.01 = 0.0004.
        // So total world extent: a few centimeters per axis (order of 0.1–0.3 m).
        const sizeX = worldMax.x - worldMin.x;
        const sizeY = worldMax.y - worldMin.y;
        const sizeZ = worldMax.z - worldMin.z;
        expect(sizeX).toBeGreaterThan(0.01);
        expect(sizeY).toBeGreaterThan(0.01);
        expect(sizeZ).toBeGreaterThan(0.01);

        // Lock in deterministic world bounds (2-decimal precision, verified against authored data)
        expect(worldMin.x).toBeCloseTo(-0.179, 2);
        expect(worldMax.x).toBeCloseTo(0.004, 2);
        expect(worldMin.y).toBeCloseTo(0.0, 2);
        expect(worldMax.y).toBeCloseTo(0.02, 2);
        expect(worldMin.z).toBeCloseTo(-0.012, 2);
        expect(worldMax.z).toBeCloseTo(0.014, 2);
    });

    // -- Materials --

    it("assigns default materials to the 3 meshes with MDL-only bindings", () => {
        const boundMeshes = result.meshes.filter((m) => m.material !== null);
        expect(boundMeshes).toHaveLength(3);
    });
});

describe("USD runtime corpus - Robot Arm (resource limit regression)", () => {
    let sourceText: string;

    beforeAll(() => {
        sourceText = readRuntimeCorpusText(RobotArmAsset.fileName);
    });

    it("rejects the real file with the old 5M token limit", async () => {
        await expect(ResolveUsdStageAsync(sourceText, "", RobotArmAsset.fileName, { maxTokenCount: 5_000_000 })).rejects.toMatchObject({
            kind: "token-count",
            limit: 5_000_000,
        });
    });

    it("parses successfully with the new 10M token default (real usage ~6.3M tokens)", async () => {
        // The real file uses ~6.3M tokens — above the old 5M default but under the new 10M.
        // Parser work is also ~6.3M, well under the unchanged 10M default.
        const stage = await ResolveUsdStageAsync(sourceText, "", RobotArmAsset.fileName, {});
        expect(stage.meshes).toHaveLength(7);
    }, 15_000);
});

describe("USD asset-path diagnostic coverage (synthetic)", () => {
    function makeUsdaWithMaterial(assetPath: string): string {
        return `#usda 1.0
(
    defaultPrim = "Root"
)
def Xform "Root" {
    def Mesh "M" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    ) {
        rel material:binding = </Root/Looks/Mat>
        int[] faceVertexCounts = [3]
        int[] faceVertexIndices = [0, 1, 2]
        point3f[] points = [(0,0,0), (1,0,0), (0,1,0)]
        uniform token subdivisionScheme = "none"
    }
    def Scope "Looks" {
        def Material "Mat" {
            token outputs:mdl:surface.connect = </Root/Looks/Mat/Shader.outputs:out>
            def Shader "Shader" {
                uniform token info:implementationSource = "sourceAsset"
                uniform asset info:mdl:sourceAsset = @test.mdl@
                asset inputs:test_texture = @${assetPath}@ (
                    colorSpace = "raw"
                )
                token outputs:out (
                    renderType = "material"
                )
            }
        }
    }
}`;
    }

    it("diagnoses a Windows drive-letter absolute path without echoing it", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial("D:\\\\Textures\\\\color.png"), "", "test.usda", {});
        const diag = stage.diagnostics.find((d) => d.path === "/Root/Looks/Mat/Shader.inputs:test_texture" && /absolute nonportable/i.test(d.message));
        expect(diag).toBeDefined();
        expect(diag!.severity).toBe("warning");
        expect(diag!.message).not.toContain("D:\\");
    });

    it("diagnoses a UNC absolute path without echoing it", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial("\\\\\\\\server\\\\share\\\\tex.png"), "", "test.usda", {});
        const diag = stage.diagnostics.find((d) => d.path === "/Root/Looks/Mat/Shader.inputs:test_texture" && /absolute nonportable/i.test(d.message));
        expect(diag).toBeDefined();
        expect(diag!.severity).toBe("warning");
    });

    it("diagnoses a Unix absolute path without echoing it", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial("/usr/local/textures/color.png"), "", "test.usda", {});
        const diag = stage.diagnostics.find((d) => d.path === "/Root/Looks/Mat/Shader.inputs:test_texture" && /absolute nonportable/i.test(d.message));
        expect(diag).toBeDefined();
        expect(diag!.severity).toBe("warning");
    });

    it("diagnoses an empty asset path", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial(""), "", "test.usda", {});
        const diag = stage.diagnostics.find((d) => d.path === "/Root/Looks/Mat/Shader.inputs:test_texture" && /empty path/i.test(d.message));
        expect(diag).toBeDefined();
        expect(diag!.severity).toBe("warning");
    });

    it("does not flag HTTP URLs as nonportable", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial("https://example.com/tex.png"), "", "test.usda", {});
        const absoluteDiag = stage.diagnostics.find((d) => /absolute nonportable/i.test(d.message));
        expect(absoluteDiag).toBeUndefined();
    });

    it("does not flag data URIs as nonportable", async () => {
        const stage = await ResolveUsdStageAsync(makeUsdaWithMaterial("data:image/png;base64,iVBOR"), "", "test.usda", {});
        const absoluteDiag = stage.diagnostics.find((d) => /absolute nonportable/i.test(d.message));
        expect(absoluteDiag).toBeUndefined();
    });
});
